package com.ziqi.codesim.pipeline;

public enum Stage0Mode {
    PARSE_FAILED,
    EMPTY_OR_TOO_SMALL,
    UNSUPPORTED_OR_MIXED_LANGUAGE,
    NO_METHOD_CLASS_CONTEXT,
    BCB_SINGLE_METHOD_FRAGMENT,
    SINGLE_METHOD_REAL_FILE,
    ONE_TO_MANY_METHOD,
    MULTI_METHOD_BALANCED,
    MULTI_METHOD_UNBALANCED
}
